apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: redis-pool2
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-pool2
  name: redis-pool2
  namespace: redis-pool2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-pool2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-pool2
    spec:
      containers:
        - image: redis
          name: redis
          resources:
            requests:
              cpu: "4"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - redis
                  - key: zone
                    operator: In
                    values:
                      - pool2
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "redis"
          effect: "NoSchedule"
status: {}
