apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: webapp-pool2
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp-pool2
  name: webapp-pool2
  namespace: webapp-pool2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-pool2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp-pool2
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            requests:
              cpu: "4"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - webapp
                  - key: zone
                    operator: In
                    values:
                      - pool1
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "webapp"
status: {}
