---
- name: setup src dir for go tools
  file:
    path: "{{ lookup('env', 'HOME') }}/go/src"
    state: directory

- name: setup bin dir for go tools
  file:
    path: "{{ lookup('env', 'HOME') }}/go/bin"
    state: directory

