---
# for role-specific vars, use the files from vars directory when possible 
# variables here will be overwritten if `vars_files` are used in plays or `include_vars` in tasks

# used when downloading binaries (e.g: go)
os: linux
arch: amd64