# fallback ver = if latest version check fails
# remove_existing checks per lang / framework

rust:
  remove_existing: false
  rustup_init: https://sh.rustup.rs 

deno:
  remove_existing: false
  install: https://deno.land/x/install/install.sh

openjdk:
  version: 11
  state: present

python:
  state: present

go:
  remove_existing: false 
  fallback_ver: go1.16.5

dotnet:
  purge_existing_msft_pkg: false
  sdk_version: 5.0

