---
- name: update and upgrade
  package:
    upgrade: yes
    update_cache: yes

- name: zsh 
  package:
    name: "{{ item }}"
  loop:
    - zsh
    - zplug

- name: starship prompt (skip confirmation)
  shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes



