---
# If the play uses become:true then
# ansible_env.HOME will point to /root whereas lookup('env', 'HOME') will be $HOME
- debug: msg="ansible_env.home => {{ ansible_env.HOME }} and lookup('env', 'HOME') -> {{ lookup('env', 'HOME') }}"

- name: zsh and zplug
  become: true
  package:
    name: "{{ item }}"
    state: "{{ zsh.state }}"
  loop:
    - bash-completion
    - zsh
    - zplug

- include_tasks: starship.yml

- include_tasks: utils.yml