# -----------------------------------------------------------
# Make sure to run init.sh from prereq/<target-env> directory prior to this 

# Test Run: ansible-playbook init.yml --check
# Specific Tags: ansible-playbook init.yml --tags precheck 

# All: ansible-playbook init.yml 
# -----------------------------------------------------------

- name: "prelaunch"
  hosts: all
  tags: prelaunch
  gather_facts: yes # needed for distro vars such as below   

  pre_tasks:
    - debug: 
        msg: "{{ ansible_distribution }}"
    - command: lsb_release -cs
      register: distro_version
    - debug: 
        msg: "{{ ansible_os_family }}" 

- name: "prereq"
  hosts: all
  tags: prereq
  become: true
  
  tasks:
    - package:
        upgrade: yes
        update_cache: yes
    - package:
        name: "{{ item }}"
      loop:
        - git
        - wget
        - curl        
        - python-apt # needed for ansible --check
        - vim
        - neovim
        - zsh
        - zplug

- name: "starship prompt"
  hosts: all
  tags: starship
  tasks:
    - name: starship prompt (skip confirmation)
      shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes

# Not using become:true for dotfiles roles
# To avoid permission issues when other tools need to create config files
- name: "dotfiles"
  hosts: all
  tags: dotfiles  
  roles:
    - dotfiles 

