# -----------------------------------------------------------
# Make sure to run init.sh from prereq/<target-env> directory prior to this 

# Test Run: ansible-playbook init.yml --check
# Specific Tags: ansible-playbook init.yml --tags precheck 

# All: ansible-playbook init.yml 
# -----------------------------------------------------------

- name: "prelaunch"
  hosts: all
  tags: prelaunch
  gather_facts: yes # needed for distro vars such as below   

  pre_tasks:
    - debug: 
        msg: "{{ ansible_distribution }}"
    - command: lsb_release -cs
      register: distro_version
    - debug: 
        msg: "{{ ansible_os_family }}" 

- name: "prereq"
  hosts: all
  tags: prereq
  become: true
  
  tasks:
    - package:
        upgrade: yes
        update_cache: yes
    - package:
        name: "{{ item }}"
      loop:
        - git
        - wget
        - curl
        - python-apt # needed for ansible --check

- name: "config"
  hosts: all
  tags: config
  become: true
  roles:
    - shell
    - dotfiles

