# -----------------------------------------------------------
# Make sure to run init.sh from prereq/<target-env> directory prior to this 

# Test Run: ansible-playbook init.yml --check
# Specific Tags: ansible-playbook init.yml --tags precheck 

# All: ansible-playbook init.yml 

# For Special variables on a given host run
# ansible -m setup localhost
# https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#special-variables

# -----------------------------------------------------------

- name: "prelaunch"
  hosts: all
  tags: prelaunch
  gather_facts: yes # needed for distro vars such as below   

  
  pre_tasks:
    - debug: 
        msg: 
          "OS Family: {{ ansible_os_family }},
           Distro: {{ ansible_distribution }},
           release: {{ ansible_distribution_release }},                      
           Distro Major Ver: {{ ansible_distribution_major_version }},          
           Distro Ver: {{ ansible_distribution_version }},             
           Arch: {{ ansible_architecture }}"     

- name: "prereq"
  hosts: all
  tags: prereq
  become: true
  
  tasks:
    - package:
        upgrade: yes
        update_cache: yes
    - package:
        name: "{{ item }}"
      loop:
        - git
        - wget
        - curl                 
        - python-apt # needed for ansible --check
        - unzip # needed for deno
        - apt-transport-https # needed for dotnet
 
- name: "common"
  hosts: all
  tags: common
  become: true

  tasks:
    - package:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - dpkg
        - lsb-release
        - software-properties-common # apt-add-repo        
        - ca-certificates            
        - openssh-client        
        - gnupg # needed for docker        
        - vim
        - neovim        
        - zsh
        - zplug        
        
- name: "starship prompt"
  hosts: all
  tags: starship
  tasks:
    - name: starship prompt (skip confirmation)
      shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes

- name: "programming languages and frameworks"
  hosts: all
  tags: programming
  vars_files: 
    - "./vars/programming.yml"    
  roles: 
    - programming

# Not using become:true for dotfiles roles
# To avoid permission issues when other tools need to create config files
- name: "dotfiles"
  hosts: all
  tags: dotfiles  
  roles:
    - dotfiles 


