- name: check $Home
  debug:
    msg: "{{ ansible_env.HOME }}"

- name: setup local bin for user
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: setup local share for user
  file:
    path: "{{ ansible_env.HOME }}/.local/share"
    state: directory

