- name: check $Home
  debug:
    msg: "{{ lookup('env', 'HOME') }}"

- name: setup local bin for user
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory

- name: setup local share for user
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share"
    state: directory

