apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"    
  name: myapp-svc
  namespace: myapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: myapp
  type: LoadBalancer
status:
  loadBalancer: {}
