- name: check $Home
  debug:
    msg: "{{ lookup('env', 'HOME') }}"

- name: setup shell config dir
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/shell"
    state: directory

- name: setup local bin for user
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory