# Starship config - goes into ~/.config/

[shell]
disabled = false
bash_indicator = "bash"
powershell_indicator = "PS"
zsh_indicator = "zsh"

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"